package org.example.lib;

import org.example.lib.configs.*;
import org.example.lib.exception.ExistingObjectException;
import org.example.lib.exception.ORMException;
import org.example.lib.utils.ConnectionUtils;

import javax.sql.DataSource;
import java.io.Serializable;

import java.nio.file.Path;
import java.sql.SQLException;
import java.util.*;
import java.util.stream.Stream;

public interface ORManager {

    static ORManager withPropertiesFrom(String filename) throws SQLException {
        Properties properties = PropertyConfiguration.readPropertiesFromFile(Path.of(filename));
        return new ORManagerImpl((DataSource) ConnectionUtils.createConnection(properties));
    }

    static ORManager withDataSource(DataSource dataSource) throws SQLException {
        return new ORManagerImpl(HikariCPDataSource.getHikariDatasourceConfiguration(dataSource));
    }

    // generate the schema in the DB
    // for given list of org.example.client.entity classes (and all related
    //  by OneToMany/ManyToOne) create a schema in DB
    void register(Class<?>... entityClasses) throws ORMException;

    // CREATE
    // save a new object to DB, set id if autogenerated
    // or merge into DB if id is present
    <T> T save(T o) throws SQLException, ORMException;

    // save a new object to DB, set id if autogenerated
    // throw if the object has id already set (except for String)
    void persist(Object o) throws ExistingObjectException, ORMException;

    // READ
    <T> Optional<T> findById(Serializable id, Class<T> cls) throws ORMException;

    // READ ALL
    <T> List<T> findAll(Class<T> cls) throws ORMException;

    // READ ALL LAZY
    <T> Iterable<T> findAllAsIterable(Class<T> cls) throws Exception; // (MEDIUM)

    <T> Stream<T> findAllAsStream(Class<T> cls);     // (OPTIONAL)

    // UPDATE
    <T> T merge(T o);   // send o -> DB row (to table)

    <T> T refresh(T o); // send o <- DB row (from table)

    // DELETE
    // set autogenerated id to null
    // return true if successfully deleted
    boolean delete(Object o);
}
